# -*- coding: utf-8 -*-
"""suc_OpenWebUI_AppImage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KBr9zIbPgi0YbTYlmBSE-PlPr4lEsJJ8
"""





!git clone https://github.com/open-webui/desktop.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/desktop

!npm install

!npm run build:linux

"""https://github.com/open-webui/desktop"""

!npm run dev

/content/desktop/dist/open-webui-desktop-0.0.1.AppImage

/content/desktop/dist/open-webui-desktop_0.0.1_amd64.deb

/content/desktop/dist/open-webui-desktop_0.0.1_amd64.snap